name: Build GraphViz Module
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7', '9.2.7', '9.4.5', '9.6.2']
        cabal: ['3.0.0.0']
        os: [ubuntu-latest]
    name: Build GraphViz Module ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Configure the build plan
        run: |
            cabal update
            cabal build -f vizdot --dry-run
          # cabal build --dry-run creates dist-newstyle/cache/plan.json
          # Keep a watch on this `cabal-3.9 build --dry-run` bug:
          # https://github.com/haskell/cabal/issues/8706
      - name: Read the Cabal cache
        uses: actions/cache@v3
        with:
            path: |
              ~/.cabal/store
              dist-newstyle
            key: |
              cabal-cache-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-${{ hashFiles('**/plan.json') }}
            restore-keys: |
              cabal-cache-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-
      - name: Build the Data.Equality.Graph.Dot module
        run: cabal build -f vizdot